### ISSUE TITLE
Do we need shaper glot to work?

### ISSUE THREAD

**Issue by EbenSorkin** [SorkinType/Danfo#9] opened 2023-10-04 02:03 UTC
Failed with ModuleNotFoundError: No module named                      
          'shaperglot'

**Comment by eliheuer** [comment] 2023-10-04 04:52
Issues like this should go in the Font Bakery issue tracker

**Comment by eliheuer** [comment] 2023-10-04 05:49
I made an issue here: https://github.com/fonttools/fontbakery/discussions/4291

**Comment by felipesanches** [comment] 2023-10-04 08:51
here's the fix: https://github.com/SorkinType/Agbalumo/pull/14

**Comment by eliheuer** [comment] 2023-10-04 08:53
Thanks @felipesanches! Should we update the GFPT to do this by default? 
https://github.com/googlefonts/googlefonts-project-template/blob/main/requirements.txt

**Comment by felipesanches** [comment] 2023-10-04 08:55
yes, please

**Comment by felipesanches** [comment] 2023-10-04 14:30
you can close this issue now that the problem is fixed

**Closed as completed** 2023-10-04 16:05 UTC
